name: Deploy GH Pages

on: [push]

jobs:
  build:
    name: Build Vue
    runs-on: ubuntu-latest
    steps:
      - name: Run Node
        uses: actions/setup-node@v1
        with:
          node-version: 8.10
      - run: |
          npm install
          npm run build
  deploy:
    name: Push to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: GitHub Pages Deploy 2
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages
          FOLDER: dist
        
