name: Deploy GH Pages

on: [push]

jobs:
  build:
    name: Deploy GH Pages
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm install
          npm run build
        
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
