name: Deploy GH Pages

on: [push]

jobs:
  build:
    name: Build Vue
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm install
          npm run build
  deploy:
    name: Push to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        with:
          BUILD_DIR: "dist/"
